name: globalopportunity
favicon: null
layout_spectrum: 0.18611629563383758
typography_spectrum: 0.8362560542300344
title: 'Creating wellness globally '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5066450496669859
  lightness: 0.9055081093683839
  saturation: 0.34619704028591514
  rhythmicContrast: 0.08017514692619443
purpose: []
